<?php

namespace SSupport\Module\Referee\UseCase\Customer;

use SSupport\Component\Core\Entity\UserInterface;
use SSupport\Component\Referee\Entity\RefereeTicketInterface;
use SSupport\Component\Referee\UseCase\Customer\RequestReferee\RequestRefereeInputInterface;
use yii\base\Model;

class RequestRefereeInputForm extends Model implements RequestRefereeInputInterface
{
    protected $ticket;
    protected $requester;

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function setTicket(RefereeTicketInterface $ticket)
    {
        $this->ticket = $ticket;

        return $this;
    }

    public function getTicket(): RefereeTicketInterface
    {
        return $this->ticket;
    }

    public function setRequester(UserInterface $requester = null)
    {
        $this->requester = $requester;

        return $this;
    }

    public function getRequester()
    {
        return $this->requester;
    }
}
