<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assign' => 'Назначенный',
    'Assign ID' => 'ID назначенного',
    'Create Ticket' => 'Создать обращение',
    'Created At' => 'Создано',
    'Customer' => 'Клиент',
    'Customer ID' => 'ID клиента',
    'Files' => 'Файлы',
    'ID' => '',
    'Message ID' => 'ID сообщения',
    'Name' => 'Имя',
    'Nickname' => 'Ник (Nickname)',
    'Path' => 'Путь',
    'Reset' => 'Сбросить',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Send' => 'Отправить',
    'Sender ID' => 'Id отправителя',
    'Size' => 'Размер',
    'Subject' => 'Тема',
    'Text' => 'Сообщение',
    'Ticket ID' => 'Id обращения',
    'Tickets' => 'Обращения',
    'Updated At' => 'Обновлено',
    'notifier_text' => 'Новое сообщение от пользователя {nickname} в обращении, его можно прочесть по ссылке: {link}.',
    'notifier_html' => 'Новое сообщение от пользователя {nickname} в обращении, его можно прочесть по {link}.',
    'message_link' => 'ссылке',
    'ticket_created_success' => 'Обращение успешно создано.',
    'to_view_ticket' => 'Для просмотра обращение необходимо {link}.',
    'authorize' => 'авторизоваться',
];
