<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assign' => '',
    'Assign ID' => '',
    'Create Ticket' => '',
    'Created At' => '',
    'Customer' => '',
    'Customer ID' => '',
    'Files' => '',
    'ID' => '',
    'Message ID' => '',
    'Name' => '',
    'Nickname' => '',
    'Path' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Send' => '',
    'Sender ID' => '',
    'Size' => '',
    'Subject' => '',
    'Text' => '',
    'Ticket ID' => '',
    'Tickets' => '',
    'Updated At' => '',
    'notifier_text' => 'Новое сообщение от пользователя {nickname} в обращении, его можно прочесть по ссылке: {link}.',
    'notifier_html' => 'Новое сообщение от пользователя {nickname} в обращении, его можно прочесть по {link}.',
    'message_link' => 'link',
    'ticket_created_success' => 'Ticket have been created successfully.',
    'to_view_ticket' => 'To view the ticket is necessary {link}.',
    'authorize' => 'log in',
];
